import { describe, it, expect } from "vitest";
import { decodeMarker } from "./decoder";

// Golden bit grids below were captured by running
// `bun run scripts/test-charuco-generator.ts` and copying its Part A output
// verbatim. Each grid is the marker's bit pattern (1 = black cell) sampled
// directly from `render_charuco_bundle`'s rendered SVG at cell centres — the
// same reference renderer whose bit-order convention `decodeMarker` must
// match (`calib-targets-print/src/render.rs::build_charuco`, LSB-first,
// row-major, set bit = black). Do not hand-compute replacements — regenerate
// with the script above if the dictionaries or codes ever change.

function toGrid(pattern: string): boolean[][] {
    return pattern.split("/").map((row) => row.split("").map((bit) => bit === "1"));
}

describe("decodeMarker", () => {
    // DICT_4X4_50, generated by
    // render_charuco_bundle(4, 4, 20, 0.75, 'DICT_4X4_50', 150)
    it("decodes DICT_4X4_50 id=0 to match the library-rendered grid", () => {
        expect(decodeMarker("0xb352", 4)).toEqual(toGrid("0100/1010/1100/1101"));
    });

    it("decodes DICT_4X4_50 id=1 to match the library-rendered grid", () => {
        expect(decodeMarker("0xa60f", 4)).toEqual(toGrid("1111/0000/0110/0101"));
    });

    it("decodes DICT_4X4_50 id=2 to match the library-rendered grid", () => {
        expect(decodeMarker("0x4b33", 4)).toEqual(toGrid("1100/1100/1101/0010"));
    });

    // DICT_5X5_100, generated by
    // render_charuco_bundle(4, 4, 20, 0.75, 'DICT_5X5_100', 150)
    it("decodes DICT_5X5_100 id=0 to match the library-rendered grid", () => {
        expect(decodeMarker("0x18564ba", 5)).toEqual(toGrid("01011/10100/10011/01010/00011"));
    });

    it("decodes DICT_5X5_100 id=1 to match the library-rendered grid", () => {
        expect(decodeMarker("0x1313f8f", 5)).toEqual(toGrid("11110/00111/11110/01000/11001"));
    });

    it("decodes DICT_5X5_100 id=2 to match the library-rendered grid", () => {
        expect(decodeMarker("0x0891e14", 5)).toEqual(toGrid("00101/00001/11100/01001/00010"));
    });

    // DICT_APRILTAG_36h11 (marker_size 6 — verified against
    // public/arucodict/DICT_APRILTAG_36h11_CODES.json, not assumed), generated
    // by render_charuco_bundle(4, 4, 24, 0.75, 'DICT_APRILTAG_36h11', 150)
    it("decodes DICT_APRILTAG_36h11 id=0 to match the library-rendered grid", () => {
        expect(decodeMarker("0x2a29d7a7b", 6)).toEqual(
            toGrid("110111/100101/111010/111001/010001/010100"),
        );
    });

    it("decodes DICT_APRILTAG_36h11 id=1 to match the library-rendered grid", () => {
        expect(decodeMarker("0x2680e74b6", 6)).toEqual(
            toGrid("011011/010010/111001/110000/000101/100100"),
        );
    });

    it("decodes DICT_APRILTAG_36h11 id=2 to match the library-rendered grid", () => {
        expect(decodeMarker("0x22d7f6ef1", 6)).toEqual(
            toGrid("100011/110111/011011/111110/101101/000100"),
        );
    });

    it("throws when marker_size^2 exceeds the 64-bit packed code", () => {
        expect(() => decodeMarker("0x0", 9)).toThrow(/exceeds the 64-bit packed code/);
    });
});
