/**
 * Content search record builder.
 * Extracts searchable metadata from processed content entries and
 * emits src/generated/content-search.ts as a typed TypeScript literal.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export interface SearchRecord {
    slug: string;
    path: string;
    type: "algorithm" | "model" | "concept";
    title: string;
    summary: string;
    tags: string[];
    category?: string;
    headings: string[];
}

/** Extract text content of <h2> and <h3> headings from rendered HTML. */
export function extractHeadings(html: string): string[] {
    const results: string[] = [];
    const regex = /<h[23][^>]*>([^<]+)<\/h[23]>/gi;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(html)) !== null) {
        const text = match[1].trim();
        if (text) results.push(text);
    }
    return results;
}

export interface SearchEntry {
    slug: string;
    type: "algorithm" | "model" | "concept";
    title: string;
    summary: string;
    tags: string[];
    category?: string;
    html: string;
}

/** Build search records from processed entries. Drafts must be pre-filtered by the caller. */
export function buildSearchRecords(entries: SearchEntry[]): SearchRecord[] {
    return entries.map((e) => {
        const path = (() => {
            switch (e.type) {
                case "algorithm": return `/algorithms/${e.slug}`;
                case "model": return `/algorithms/models/${e.slug}`;
                case "concept": return `/concepts/${e.slug}`;
            }
        })();

        return {
            slug: e.slug,
            path,
            type: e.type,
            title: e.title,
            summary: e.summary,
            tags: e.tags,
            ...(e.category !== undefined ? { category: e.category } : {}),
            headings: extractHeadings(e.html),
        };
    });
}

/**
 * Write src/generated/content-search.ts as a typed TypeScript literal.
 */
export function emitContentSearch(records: SearchRecord[], outDir: string): void {
    const filePath = join(outDir, "content-search.ts");

    const lines: string[] = [
        "// Auto-generated by scripts/content-build.ts — do not edit manually.",
        "",
        "export interface SearchRecord {",
        "    slug: string;",
        "    path: string;",
        "    type: \"algorithm\" | \"model\" | \"concept\";",
        "    title: string;",
        "    summary: string;",
        "    tags: string[];",
        "    category?: string;",
        "    headings: string[];",
        "}",
        "",
        `export const searchRecords: SearchRecord[] = ${JSON.stringify(records, null, 2)};`,
        "",
    ];

    writeFileSync(filePath, lines.join("\n"), "utf-8");
}
