import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import matter from "gray-matter";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkRehype from "remark-rehype";
import rehypeSanitize from "rehype-sanitize";
import rehypeStringify from "rehype-stringify";

import {
    blogFrontmatterSchema,
    algorithmFrontmatterSchema,
} from "../src/lib/content/schema.ts";
import type { BlogEntry, AlgorithmEntry } from "../src/lib/content/schema.ts";
import type { ZodType } from "zod";

const CONTENT_DIR = join(import.meta.dir, "..", "content");
const OUTPUT_FILE = join(import.meta.dir, "..", "src", "generated", "content-manifest.ts");

function blogSlug(filename: string): string {
    // YYYY-MM-DD-title.md → title
    return basename(filename, ".md").replace(/^\d{4}-\d{2}-\d{2}-/, "");
}

function algoSlug(filename: string): string {
    return basename(filename, ".md");
}

async function renderMarkdown(content: string): Promise<string> {
    const result = await unified()
        .use(remarkParse)
        .use(remarkGfm)
        .use(remarkRehype)
        .use(rehypeSanitize)
        .use(rehypeStringify)
        .process(content);
    return String(result);
}

async function processDirectory<T>(
    dir: string,
    schema: ZodType<T>,
    slugFn: (filename: string) => string,
): Promise<{ slug: string; frontmatter: T; html: string }[]> {
    if (!existsSync(dir)) return [];

    const files = readdirSync(dir).filter((f) => f.endsWith(".md"));
    const entries: { slug: string; frontmatter: T; html: string }[] = [];

    for (const file of files) {
        const raw = readFileSync(join(dir, file), "utf-8");
        const { data, content } = matter(raw);
        const parsed = schema.parse(data);
        const html = await renderMarkdown(content);
        entries.push({ slug: slugFn(file), frontmatter: parsed, html });
    }

    return entries;
}

function serializeDate(value: unknown): string {
    if (value instanceof Date) return value.toISOString().split("T")[0];
    return String(value);
}

function serializeBlogEntry(entry: { slug: string; frontmatter: Record<string, unknown>; html: string }): BlogEntry {
    const { date, updated, ...rest } = entry.frontmatter;
    return {
        slug: entry.slug,
        frontmatter: {
            ...rest,
            date: serializeDate(date),
            ...(updated !== undefined ? { updated: serializeDate(updated) } : {}),
        } as BlogEntry["frontmatter"],
        html: entry.html,
    };
}

function generateManifest(blogPosts: BlogEntry[], algorithmPages: AlgorithmEntry[]): void {
    const outDir = join(OUTPUT_FILE, "..");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    const lines = [
        '// Auto-generated by scripts/content-build.ts — do not edit manually.',
        'import type { BlogEntry, AlgorithmEntry } from "../lib/content/schema.ts";',
        "",
        `export const blogPosts: BlogEntry[] = ${JSON.stringify(blogPosts, null, 2)};`,
        "",
        `export const algorithmPages: AlgorithmEntry[] = ${JSON.stringify(algorithmPages, null, 2)};`,
        "",
    ];
    writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
}

async function main(): Promise<void> {
    const rawBlogPosts = await processDirectory(
        join(CONTENT_DIR, "blog"),
        blogFrontmatterSchema,
        blogSlug,
    );

    // Serialize dates and sort by date descending
    const blogPosts = rawBlogPosts
        .map((e) => serializeBlogEntry(e as { slug: string; frontmatter: Record<string, unknown>; html: string }))
        .sort((a, b) => b.frontmatter.date.localeCompare(a.frontmatter.date));

    const algorithmPages = await processDirectory(
        join(CONTENT_DIR, "algorithms"),
        algorithmFrontmatterSchema,
        algoSlug,
    );

    generateManifest(blogPosts, algorithmPages as AlgorithmEntry[]);

    console.log(
        `content:build — ${blogPosts.length} blog post(s), ${algorithmPages.length} algorithm page(s) → ${OUTPUT_FILE}`,
    );
}

main().catch((err) => {
    console.error("content:build failed:", err);
    process.exit(1);
});
