/**
 * Content search record builder.
 * Extracts searchable metadata from processed content entries and
 * emits src/generated/content-search.ts as a typed TypeScript literal.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export interface SearchRecord {
    slug: string;
    path: string;
    type: "algorithm" | "model" | "concept";
    title: string;
    summary: string;
    tags: string[];
    /** Unified domain taxonomy value (replaces per-kind category). */
    domain?: string;
    headings: string[];
    /** Source paper authors, joined from `frontmatter.sources.primary`. */
    authors?: string[];
    /** Source paper venue (e.g. "CVPR", "ECCV"). */
    venue?: string;
}

/** Extract text content of <h2> and <h3> headings from rendered HTML. */
export function extractHeadings(html: string): string[] {
    const results: string[] = [];
    const regex = /<h[23][^>]*>([^<]+)<\/h[23]>/gi;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(html)) !== null) {
        const text = match[1].trim();
        if (text) results.push(text);
    }
    return results;
}

export interface SearchEntry {
    slug: string;
    type: "algorithm" | "model" | "concept";
    title: string;
    summary: string;
    tags: string[];
    /** Unified domain taxonomy value. */
    domain?: string;
    html: string;
    /** Optional resolved primary-paper metadata (authors, venue). */
    primary?: { authors?: string[]; venue?: string };
}

/** Build search records from processed entries. Drafts must be pre-filtered by the caller. */
export function buildSearchRecords(entries: SearchEntry[]): SearchRecord[] {
    return entries.map((e) => {
        // Single global slug namespace: every atlas page routes through /atlas/<slug>.
        const path = `/atlas/${e.slug}`;

        return {
            slug: e.slug,
            path,
            type: e.type,
            title: e.title,
            summary: e.summary,
            tags: e.tags,
            ...(e.domain !== undefined ? { domain: e.domain } : {}),
            headings: extractHeadings(e.html),
            ...(e.primary?.authors && e.primary.authors.length > 0 ? { authors: e.primary.authors } : {}),
            ...(e.primary?.venue ? { venue: e.primary.venue } : {}),
        };
    });
}

/**
 * Write src/generated/content-search.ts as a typed TypeScript literal.
 */
export function emitContentSearch(records: SearchRecord[], outDir: string): void {
    const filePath = join(outDir, "content-search.ts");

    const lines: string[] = [
        "// Auto-generated by scripts/content-build.ts — do not edit manually.",
        "",
        "export interface SearchRecord {",
        "    slug: string;",
        "    path: string;",
        "    type: \"algorithm\" | \"model\" | \"concept\";",
        "    title: string;",
        "    summary: string;",
        "    tags: string[];",
        "    domain?: string;",
        "    headings: string[];",
        "    authors?: string[];",
        "    venue?: string;",
        "}",
        "",
        `export const searchRecords: SearchRecord[] = ${JSON.stringify(records, null, 2)};`,
        "",
    ];

    writeFileSync(filePath, lines.join("\n"), "utf-8");
}
